import type { AssessmentResult, LocationEvidence } from "../types";

export const googleLocationEvidence: LocationEvidence = {
  portfolio_id: "google_public_data_centers",
  portfolio_version: "2026-08-10",
  operator: "Google",
  facility_status: "under_construction",
  facility_source_title: "Google Data Center Locations",
  facility_source_url: "https://www.datacenters.google/locations/",
  source_checked_at: "2026-08-10",
  coordinate_source_url: "https://nominatim.openstreetmap.org/",
  coordinate_basis: "locality_centroid",
  coordinate_confidence: "low",
  business_inputs_basis: "screening_defaults",
  methodology_reference_url: "https://www.gstatic.com/gumdrop/sustainability/2023-data-center-water-risk-framework-whitepaper.pdf",
  asset_scope: "google_public_data_center_location",
  note: "Screening proxy only.",
};

export function assessmentFixture(overrides: Partial<AssessmentResult> = {}): AssessmentResult {
  return {
    assessment_id: "assessment-phoenix",
    status: "complete",
    site: {
      id: "phoenix-1",
      name: "Phoenix candidate",
      latitude: 33.4484,
      longitude: -112.074,
      project_type: "retrofit",
      cost_priority: "constrained",
      uptime_constraint: "no_outage",
      growth_3y: "high",
      pue: 1.62,
      wue_l_per_kwh: 0.4,
    },
    source: {
      water: {
        provider: "aqueduct_esri",
        data_status: "available",
        dataset: "WRI Aqueduct 4.0 Baseline Annual",
        dataset_vintage: "2023",
        retrieved_at: "2026-08-09T12:00:00Z",
        source_url: "https://example.test/aqueduct",
        attribution: "Source: WRI Aqueduct",
        cache: { hit: false, stale: false },
        geography: { gid_0: "USA", name_0: "United States", name_1: "Arizona" },
        fields: {
          bws_score: 5,
          bws_cat: 4,
          bws_label: "Extremely High (>80%)",
          w_awr_def_tot_score: 3.01,
          w_awr_def_tot_cat: 3,
          w_awr_def_tot_label: "High",
          w_awr_elp_tot_score: 3.13,
          w_awr_elp_tot_cat: 3,
          w_awr_elp_tot_label: "High",
          w_awr_smc_tot_score: 2.31,
          w_awr_smc_tot_cat: 2,
          w_awr_smc_tot_label: "Medium-High",
        },
      },
      grid: {
        provider: "ember",
        data_status: "available",
        dataset: "Ember Yearly Carbon Intensity",
        dataset_vintage: "2024",
        source_url: "https://example.test/ember",
        attribution: "Public proxy — Ember (CC BY 4.0)",
        factor_basis: "national lifecycle generation intensity",
        unit: "gCO2e/kWh",
        transport: "public_csv",
        retrieved_at: "2026-08-09T12:00:00Z",
        cache: { hit: false, stale: false },
        entity: "United States of America",
        entity_code: "USA",
        date: "2024",
        emissions_intensity_gco2_per_kwh: 367,
      },
    },
    policy_v1: {
      version: "1.0.0",
      confidence: "high",
      scores: {
        environmental_priority: 72.94,
        sensitivity: {
          baseline_water_stress: { source_score: 5, source_category: 4, source_label: "Extremely High (>80%)", normalized: 1, environmental_priority: 72.94, status: "scored" },
          default_overall: { source_score: 3.01, source_category: 3, source_label: "High", normalized: 0.602, environmental_priority: 53.04, status: "scored" },
          electric_power: { source_score: 3.13, source_category: 3, source_label: "High", normalized: 0.626, environmental_priority: 54.24, status: "scored" },
          semiconductor: { source_score: 2.31, source_category: 2, source_label: "Medium-High", normalized: 0.462, environmental_priority: 46.04, status: "scored" },
        },
        sensitivity_range: { minimum: 46.04, maximum: 72.94 },
        material_divergence_warning: true,
        rank_reversal_warning: false,
      },
      matrix_cell: { id: "high_or_arid", label: "Water-constrained location", water_band: "high_or_arid", carbon_band: "moderate" },
      recommendations: {
        preferred: ["Dry cooling systems"],
        conditional: ["Adaptive hybrid cooling with a binding water budget"],
        excluded: ["Unconstrained evaporative cooling"],
        energy_procurement_lever: { category: "Renewable PPA assessment", priority: "medium", affects_location_based_score: false, rationale: "Evaluate procurement separately; it does not change the location-based factor or CUE." },
      },
      delivery: { immediate: ["Validate sub-metered cooling energy and water use"], maintenance_window: ["Schedule intrusive retrofit work"], expansion: ["Apply the preferred architecture to planned capacity"] },
      business_tradeoffs: ["Environmental priority remains unchanged while delivery is staged."],
      proxy_metrics: { cue_location_based_kgco2e_per_kwh_it: 0.59, factor_basis: "location-based" },
    },
    warnings: ["Electric Power and Semiconductor views are proxy sensitivities, not WRI Data Center presets."],
    created_at: "2026-08-09T12:00:00Z",
    ...overrides,
  };
}
